# Generated by Django 4.2.3 on 2023-08-01 18:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN1APP', '0002_product1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialisation', models.CharField(choices=[('Chest', 'Chest'), ('Heart', 'Heart'), ('General', 'General'), ('Orthopaedic', 'Orthopaedic')], max_length=50)),
                ('contact_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('location', models.CharField(max_length=100)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMIN1APP.employee1')),
            ],
        ),
    ]
