# Generated by Django 4.2.3 on 2023-08-01 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN1APP', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_schedule', models.DateField()),
                ('time_of_schedule', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMIN1APP.doctor')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMIN1APP.employee1')),
            ],
        ),
    ]
