# Generated by Django 4.2.3 on 2023-08-05 16:55

import ADMIN1APP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN1APP', '0005_deal'),
    ]

    
