# Generated by Django 4.2.3 on 2023-08-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN1APP', '0007_alter_doctor_specialisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
